
CROSS_COMPILE = 
CC=$(CROSS_COMPILE)g++
LD :=$(CROSS_COMPILE)g++
LINK=$(CROSS_COMPILE)g++
TARGET = pi_marlin

_OBJ =    src/core/serial.o    src/core/utility.o    src/feature/babystep.o    src/feature/backlash.o    src/feature/baricuda.o    src/feature/bedlevel/abl/abl.o    src/feature/bedlevel/bedlevel.o    src/feature/bedlevel/mbl/mesh_bed_leveling.o    src/feature/bedlevel/ubl/ubl.o    src/feature/bedlevel/ubl/ubl_G29.o    src/feature/bedlevel/ubl/ubl_motion.o    src/feature/binary_stream.o src/feature/cooler.o     src/feature/bltouch.o    src/feature/cancel_object.o    src/feature/caselight.o    src/feature/closedloop.o    src/feature/controllerfan.o    src/feature/dac/dac_dac084s085.o    src/feature/dac/dac_mcp4728.o    src/feature/dac/stepper_dac.o    src/feature/digipot/digipot_mcp4018.o    src/feature/digipot/digipot_mcp4451.o src/feature/encoder_i2c.o src/feature/e_parser.o   src/feature/direct_stepping.o    src/feature/fanmux.o    src/feature/filwidth.o    src/feature/fwretract.o    src/feature/host_actions.o  src/feature/max7219.o   src/feature/hotend_idle.o    src/feature/joystick.o    src/feature/leds/blinkm.o    src/feature/leds/leds.o    src/feature/leds/neopixel.o    src/feature/leds/pca9632.o    src/feature/leds/printer_event_leds.o    src/feature/leds/tempstat.o    src/feature/power_monitor.o    src/feature/mixing.o    src/feature/pause.o    src/feature/power.o    src/feature/powerloss.o  src/feature/probe_temp_comp.o  src/feature/mmu/mmu2.o src/feature/mmu/mmu.o    src/feature/runout.o  src/feature/stepper_driver_safety.o src/feature/tramming.o src/feature/meatpack.o   src/feature/repeat.o    src/feature/solenoid.o    src/feature/spindle_laser.o    src/feature/tmc_util.o  src/feature/twibus.o  src/feature/e_parser.o  src/feature/hotend_idle.o  src/feature/z_stepper_align.o  src/feature/direct_stepping.o        src/feature/twibus.o     \
             src/HAL/HAL_PANDAPI/eeprom.o src/HAL/HAL_PANDAPI/HAL.o    src/HAL/HAL_PANDAPI/HAL_SPI.o    src/HAL/HAL_PANDAPI/MarlinSerial.o        src/HAL/HAL_PANDAPI/Servo.o       src/HAL/HAL_PANDAPI/watchdog.o    src/HAL/shared/backtrace/backtrace.o    src/HAL/shared/backtrace/unwarm.o    src/HAL/shared/backtrace/unwarmbytab.o    src/HAL/shared/backtrace/unwarmmem.o    src/HAL/shared/backtrace/unwarm_arm.o    src/HAL/shared/backtrace/unwarm_thumb.o    src/HAL/shared/backtrace/unwinder.o    src/HAL/shared/backtrace/unwmemaccess.o   src/HAL/shared/eeprom_if_i2c.o  src/HAL/shared/Delay.o src/HAL/shared/HAL_MinSerial.o  src/HAL/shared/eeprom_api.o    src/HAL/shared/eeprom_if_spi.o           src/HAL/shared/servo.o    src/lcd/dogm/lcdprint_u8g.o    src/lcd/dogm/status_screen_DOGM.o    src/lcd/dogm/status_screen_lite_ST7920.o         src/lcd/dogm/u8g_dev_st7565_64128n_HAL.o    src/lcd/dogm/u8g_dev_st7920_128x64_HAL.o       src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.o    src/lcd/dogm/u8g_fontutf8.o   src/lcd/dogm/marlinui_DOGM.o  src/lcd/dogm/U8glib.o src/lcd/dogm/U8glibPrint.o   src/lcd/dogm/ultralcd_st7920_u8glib_rrd_AVR.o     src/lcd/dwin/dwin_lcd.o    src/lcd/extui/lib/dgus/DGUSDisplay.o    src/lcd/extui/lib/dgus/DGUSScreenHandler.o  src/lcd/extui/lib/dgus/pandapi/DGUSScreenHandler.o src/lcd/extui/lib/dgus/pandapi/DGUSDisplayDef.o src/lcd/extui/lib/dgus/mks/DGUSDisplayDef.o  src/lcd/extui/lib/dgus/mks/DGUSScreenHandler.o src/lcd/extui/ui_api.o src/lcd/extui/nextion_lcd.o src/lcd/extui/malyan_lcd.o  src/lcd/extui/dgus_lcd.o   \
                   src/lcd/fontutils.o         src/lcd/lcdprint.o    src/lcd/menu/game/brickout.o    src/lcd/menu/game/game.o    src/lcd/menu/game/invaders.o    src/lcd/menu/game/maze.o    src/lcd/menu/game/snake.o    src/lcd/menu/menu.o    src/lcd/menu/menu_advanced.o    src/lcd/menu/menu_backlash.o    src/lcd/menu/menu_bed_corners.o    src/lcd/menu/menu_bed_leveling.o    src/lcd/menu/menu_cancelobject.o    src/lcd/menu/menu_configuration.o    src/lcd/menu/menu_language.o    src/lcd/menu/menu_delta_calibrate.o    src/lcd/menu/menu_filament.o    src/lcd/menu/menu_game.o    src/lcd/menu/menu_info.o    src/lcd/menu/menu_job_recovery.o    src/lcd/menu/menu_led.o    src/lcd/menu/menu_main.o    src/lcd/menu/menu_media.o    src/lcd/menu/menu_mixer.o    src/lcd/menu/menu_mmu2.o    src/lcd/menu/menu_motion.o    src/lcd/menu/menu_spindle_laser.o    src/lcd/menu/menu_temperature.o    src/lcd/menu/menu_tmc.o    src/lcd/menu/menu_tune.o    src/lcd/menu/menu_ubl.o    src/lcd/marlinui.o    src/libs/buzzer.o    src/libs/crc16.o    src/libs/heatshrink/heatshrink_decoder.o    src/libs/hex_print.o    src/libs/W25Qxx.o      src/libs/least_squares_fit.o    src/libs/nozzle.o    src/libs/numtostr.o    src/libs/stopwatch.o    src/libs/vector_3.o    src/MarlinCore.o    src/module/settings.o    src/module/delta.o    src/module/endstops.o    src/module/motion.o    src/module/planner.o    src/module/planner_bezier.o    src/module/printcounter.o    src/module/probe.o    src/module/scara.o    src/module/servo.o    src/module/stepper/indirection.o         src/module/stepper/TMC26X.o    src/module/stepper/trinamic.o    src/module/stepper.o    src/module/temperature.o    src/module/tool_change.o    src/sd/cardreader.o    src/sd/Sd2Card.o    src/sd/SdBaseFile.o    src/sd/SdFatUtil.o    src/sd/SdFile.o    src/sd/SdVolume.o      

_OBJ_G =   src/gcode/bedlevel/abl/G29.o    src/gcode/bedlevel/abl/M421.o    src/gcode/bedlevel/G26.o    src/gcode/bedlevel/G42.o    src/gcode/bedlevel/M420.o    src/gcode/bedlevel/mbl/G29.o    src/gcode/bedlevel/mbl/M421.o    src/gcode/bedlevel/ubl/G29.o    src/gcode/bedlevel/ubl/M421.o    src/gcode/calibrate/G28.o    src/gcode/calibrate/G33.o    src/gcode/calibrate/G34_M422.o    src/gcode/calibrate/G425.o \
		src/gcode/calibrate/M100.o    src/gcode/calibrate/M12.o    src/gcode/calibrate/M425.o    src/gcode/calibrate/M48.o    src/gcode/calibrate/M665.o    src/gcode/calibrate/M666.o    src/gcode/calibrate/M852.o    src/gcode/config/M200-M205.o    src/gcode/config/M217.o    src/gcode/config/M218.o    src/gcode/config/M220.o    src/gcode/config/M221.o    src/gcode/config/M281.o    src/gcode/config/M301.o    src/gcode/config/M302.o    src/gcode/config/M304.o    src/gcode/config/M305.o    src/gcode/config/M43.o    src/gcode/config/M540.o    src/gcode/config/M575.o    src/gcode/config/M92.o    src/gcode/control/M108_M112_M410.o    src/gcode/control/M111.o    src/gcode/control/M120_M121.o    src/gcode/control/M17_M18_M84.o    src/gcode/control/M211.o    src/gcode/control/M226.o    src/gcode/control/M280.o    src/gcode/control/M3-M5.o    src/gcode/control/M350_M351.o    src/gcode/control/M380_M381.o    src/gcode/control/M400.o    src/gcode/control/M42.o    src/gcode/control/M605.o    src/gcode/control/M7-M9.o    src/gcode/control/M80_M81.o    src/gcode/control/M85.o    src/gcode/control/M997.o    src/gcode/control/M999.o    src/gcode/control/T.o    src/gcode/eeprom/M500-M504.o    src/gcode/feature/advance/M900.o    src/gcode/feature/baricuda/M126-M129.o    src/gcode/feature/camera/M240.o    src/gcode/feature/cancel/M486.o    src/gcode/feature/caselight/M355.o    src/gcode/feature/clean/G12.o    src/gcode/feature/digipot/M907-M910.o    src/gcode/feature/filwidth/M404-M407.o    src/gcode/feature/fwretract/G10_G11.o    src/gcode/feature/fwretract/M207-M209.o    src/gcode/feature/i2c/M260_M261.o                 src/gcode/feature/leds/M150.o    src/gcode/feature/leds/M7219.o    src/gcode/feature/macro/M810-M819.o    src/gcode/feature/mixing/M163-M165.o    src/gcode/feature/mixing/M166.o    src/gcode/feature/pause/G27.o    src/gcode/feature/pause/M125.o    src/gcode/feature/pause/M600.o    src/gcode/feature/pause/M603.o    src/gcode/feature/pause/M701_M702.o    src/gcode/feature/powerloss/M1000.o    src/gcode/feature/powerloss/M413.o    src/gcode/feature/prusa_MMU2/M403.o    src/gcode/feature/runout/M412.o \
    src/gcode/feature/trinamic/M122.o    src/gcode/feature/trinamic/M569.o    src/gcode/feature/trinamic/M906.o    src/gcode/feature/trinamic/M911-M914.o    src/gcode/gcode.o    src/gcode/geometry/G17-G19.o    src/gcode/geometry/G53-G59.o    src/gcode/geometry/G92.o    src/gcode/geometry/M206_M428.o    src/gcode/host/M110.o    src/gcode/host/M113.o    src/gcode/host/M114.o    src/gcode/host/M115.o    src/gcode/host/M118.o    src/gcode/host/M119.o    src/gcode/host/M16.o    src/gcode/host/M876.o    src/gcode/lcd/M0_M1.o    src/gcode/lcd/M117.o    src/gcode/lcd/M145.o    src/gcode/lcd/M250.o    src/gcode/lcd/M300.o    src/gcode/lcd/M73.o    src/gcode/motion/G0_G1.o    src/gcode/motion/G2_G3.o    src/gcode/motion/G4.o    src/gcode/motion/G5.o    src/gcode/motion/G80.o    src/gcode/motion/M290.o    src/gcode/parser.o    src/gcode/probe/G30.o    src/gcode/probe/G31_G32.o    src/gcode/probe/G38.o    src/gcode/probe/M401_M402.o    src/gcode/probe/M851.o    src/gcode/probe/M951.o    src/gcode/queue.o    src/gcode/scara/M360-M364.o   src/gcode/sd/M1001.o  src/gcode/sd/M20.o    src/gcode/sd/M21_M22.o    src/gcode/sd/M23.o    src/gcode/sd/M24_M25.o    src/gcode/sd/M26.o    src/gcode/sd/M27.o    src/gcode/sd/M28_M29.o    src/gcode/sd/M30.o    src/gcode/sd/M32.o    src/gcode/sd/M33.o    src/gcode/sd/M34.o    src/gcode/sd/M524.o    src/gcode/sd/M928.o    src/gcode/stats/M31.o    src/gcode/stats/M75-M78.o    src/gcode/temp/M104_M109.o    src/gcode/temp/M105.o    src/gcode/temp/M106_M107.o    src/gcode/temp/M140_M190.o    src/gcode/temp/M141_M191.o    src/gcode/temp/M155.o    src/gcode/temp/M303.o    src/gcode/units/G20_G21.o    src/gcode/units/M149.o    src/gcode/units/M82_M83.o

_OBJ_U8 = 		   src/lcd/utility/u8g_bitmap.o  src/lcd/utility/u8g_circle.o  src/lcd/utility/u8g_clip.o  src/lcd/utility/u8g_com_api_16gr.o  src/lcd/utility/u8g_com_api.o  src/lcd/utility/u8g_com_arduino_attiny85_hw_spi.o  src/lcd/utility/u8g_com_arduino_common.o  src/lcd/utility/u8g_com_arduino_fast_parallel.o  src/lcd/utility/u8g_com_arduino_hw_spi.o  src/lcd/utility/u8g_com_arduino_hw_usart_spi.o  src/lcd/utility/u8g_com_arduino_no_en_parallel.o  src/lcd/utility/u8g_com_arduino_parallel.o  src/lcd/utility/u8g_com_arduino_port_d_wr.o    src/lcd/utility/u8g_com_arduino_st7920_custom.o  src/lcd/utility/u8g_com_arduino_st7920_hw_spi.o  src/lcd/utility/u8g_com_arduino_st7920_spi.o  src/lcd/utility/u8g_com_arduino_std_sw_spi.o  src/lcd/utility/u8g_com_arduino_sw_spi.o  src/lcd/utility/u8g_com_arduino_t6963.o    src/lcd/utility/u8g_com_atmega_hw_spi.o  src/lcd/utility/u8g_com_atmega_parallel.o  src/lcd/utility/u8g_com_atmega_st7920_hw_spi.o  src/lcd/utility/u8g_com_atmega_st7920_spi.o  src/lcd/utility/u8g_com_atmega_sw_spi.o    src/lcd/utility/u8g_com_io.o  src/lcd/utility/u8g_com_msp430_hw_spi.o  src/lcd/utility/u8g_com_null.o  src/lcd/utility/u8g_com_raspberrypi_hw_spi.o     src/lcd/utility/u8g_com_std_sw_spi.o  src/lcd/utility/u8g_cursor.o  src/lcd/utility/u8g_delay.o  src/lcd/utility/u8g_dev_a2_micro_printer.o  src/lcd/utility/u8g_dev_flipdisc_2x7.o  src/lcd/utility/u8g_dev_gprof.o \
		src/lcd/utility/u8g_dev_ht1632.o  src/lcd/utility/u8g_dev_ili9325d_320x240.o  src/lcd/utility/u8g_dev_ks0108_128x64.o  src/lcd/utility/u8g_dev_lc7981_160x80.o  src/lcd/utility/u8g_dev_lc7981_240x128.o  src/lcd/utility/u8g_dev_lc7981_240x64.o  src/lcd/utility/u8g_dev_lc7981_320x64.o  src/lcd/utility/u8g_dev_ld7032_60x32.o  src/lcd/utility/u8g_dev_null.o  src/lcd/utility/u8g_dev_pcd8544_84x48.o  src/lcd/utility/u8g_dev_pcf8812_96x65.o  src/lcd/utility/u8g_dev_sbn1661_122x32.o             src/lcd/utility/u8g_dev_ssd1322_nhd31oled_bw.o  src/lcd/utility/u8g_dev_ssd1322_nhd31oled_gr.o  src/lcd/utility/u8g_dev_ssd1325_nhd27oled_bw.o  src/lcd/utility/u8g_dev_ssd1325_nhd27oled_bw_new.o  src/lcd/utility/u8g_dev_ssd1325_nhd27oled_gr.o  src/lcd/utility/u8g_dev_ssd1325_nhd27oled_gr_new.o    src/lcd/utility/u8g_dev_ssd1351_128x128.o  src/lcd/utility/u8g_dev_ssd1353_160x128.o  src/lcd/utility/u8g_dev_st7565_64128n.o  src/lcd/utility/u8g_dev_st7565_dogm128.o  src/lcd/utility/u8g_dev_st7565_dogm132.o  src/lcd/utility/u8g_dev_st7565_lm6059.o  src/lcd/utility/u8g_dev_st7565_lm6063.o  src/lcd/utility/u8g_dev_st7565_nhd_c12832.o  src/lcd/utility/u8g_dev_st7565_nhd_c12864.o  src/lcd/utility/u8g_dev_st7687_c144mvgd.o  src/lcd/utility/u8g_dev_st7920_128x64.o  src/lcd/utility/u8g_dev_st7920_192x32.o  src/lcd/utility/u8g_dev_st7920_202x32.o  src/lcd/utility/u8g_dev_t6963_128x128.o  src/lcd/utility/u8g_dev_t6963_128x64.o  src/lcd/utility/u8g_dev_t6963_240x128.o  src/lcd/utility/u8g_dev_t6963_240x64.o  src/lcd/utility/u8g_dev_tls8204_84x48.o  src/lcd/utility/u8g_dev_uc1601_c128032.o  src/lcd/utility/u8g_dev_uc1608_240x128.o  src/lcd/utility/u8g_dev_uc1608_240x64.o  src/lcd/utility/u8g_dev_uc1610_dogxl160.o        src/lcd/utility/u8g_dev_uc1701_dogs102.o  src/lcd/utility/u8g_dev_uc1701_mini12864.o  src/lcd/utility/u8g_ellipse.o  src/lcd/utility/u8g_font.o  src/lcd/utility/u8g_font_data.o   src/lcd/utility/u8g_line.o \
		src/lcd/utility/u8g_ll_api.o  src/lcd/utility/u8g_page.o  src/lcd/utility/u8g_pb14v1.o  src/lcd/utility/u8g_pb16h1.o  src/lcd/utility/u8g_pb16h2.o  src/lcd/utility/u8g_pb16v1.o  src/lcd/utility/u8g_pb16v2.o  src/lcd/utility/u8g_pb32h1.o  src/lcd/utility/u8g_pb8h1.o  src/lcd/utility/u8g_pb8h1f.o  src/lcd/utility/u8g_pb8h2.o  src/lcd/utility/u8g_pb8h8.o  src/lcd/utility/u8g_pb8v1.o  src/lcd/utility/u8g_pb8v2.o  src/lcd/utility/u8g_pb.o  src/lcd/utility/u8g_pbxh16.o  src/lcd/utility/u8g_pbxh24.o  src/lcd/utility/u8g_polygon.o  src/lcd/utility/u8g_rect.o  src/lcd/utility/u8g_rot.o  src/lcd/utility/u8g_scale.o  src/lcd/utility/u8g_state.o  src/lcd/utility/u8g_u16toa.o  src/lcd/utility/u8g_u8toa.o  src/lcd/utility/u8g_virtual_screen.o \

_OBJ_TMC =    lib/TMCStepper-master/src/source/CHOPCONF.o lib/TMCStepper-master/src/source/PWMCONF.o   lib/TMCStepper-master/src/source/COOLCONF.o lib/TMCStepper-master/src/source/RAMP_STAT.o   lib/TMCStepper-master/src/source/DRV_CONF.o lib/TMCStepper-master/src/source/SERIAL_SWITCH.o         lib/TMCStepper-master/src/source/DRV_STATUS.o  lib/TMCStepper-master/src/source/SHORT_CONF.o  lib/TMCStepper-master/src/source/TMC2208Stepper.o  lib/TMCStepper-master/src/source/TMC2209Stepper.o        lib/TMCStepper-master/src/source/TMCStepper.o  lib/TMCStepper-master/src/source/ENCMODE.o  lib/TMCStepper-master/src/source/SW_MODE.o    lib/TMCStepper-master/src/source/GCONF.o   lib/TMCStepper-master/src/source/IHOLD_IRUN.o   

OBJ = $(patsubst %,%,$(_OBJ_TMC) $(_OBJ) $(_OBJ_G) $(_OBJ_U8) )
 
AllDirs := $(shell ls -R | grep '^\./.*:$$' | awk '{gsub(":","");print}') .
CPPFLAGS = $(foreach n,$(AllDirs) , -I$(n))
  
INC = -I./  -I./src/lcd/dogm  -I/home/pi/src/CMSIS -I/home/pi/src/utility -ITMC2208Stepper -I/home/pi/src/CMSIS-W -I./lib/TMCStepper-master/src/source/-I./lib/TMCStepper-master/src/ -I./lib/NeoPixel_LED/ -Wall -g0 -lm
CFLAGS = -O0 -c     -std=c++11 -D PANDAPI
LIBS = -lpi -lwiringPi -lpthread -L ./

_DEPS =    $(shell find  *.h)  
DEPS = $(patsubst %,%,$(_DEPS))

all: $(TARGET) 
%.o: %.cpp $(DEPS)	
	@$(CC) $(CPPFLAGS) $(CFLAGS) -Wall -cpp $< -o $@  
	#$(CC) $(INC) $(CFLAGS) -Wall -cpp $^ -o $@  
	
$(TARGET): $(OBJ)
	@$(LINK) -o $(TARGET) $(OBJ) ${LIBS} 
	$(CROSS_COMPILE)strip pi_marlin



clean:
	#find . -type f | xargs touch
	rm -f pi_marlin $(OBJ)  
